# Generated by Django 3.2.4 on 2021-06-09 04:13

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=apps.accounts.models.UserEmailField(max_length=254, unique=True),
        ),
    ]
