# Generated by Django 3.2.4 on 2021-06-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=100)),
                ('panel_type', models.CharField(choices=[('lang-pie', 'pie chart of languages used'), ('lang-bar', 'bar chart of languages used')], max_length=100)),
            ],
        ),
    ]
