# Generated by Django 3.2.4 on 2021-06-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='repo_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
