# Generated by Django 3.2.4 on 2021-06-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0002_dashboardpanel_repo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='style',
            field=models.CharField(choices=[('lang-pie', 'pie chart of languages used'), ('lang-bar', 'bar chart of languages used')], default='DefaultStyle', max_length=40),
        ),
        migrations.AlterField(
            model_name='dashboardpanel',
            name='panel_type',
            field=models.CharField(choices=[('DefaultStyle', 'Defaultstyle'), ('DarkSolarizedStyle', 'Darksolarizedstyle'), ('LightSolarizedStyle', 'Lightsolarizedstyle'), ('LightStyle', 'Lightstyle'), ('CleanStyle', 'Cleanstyle'), ('RedBlueStyle', 'Redbluestyle'), ('DarkColorizedStyle', 'Darkcolorizedstyle'), ('LightColorizedStyle', 'Lightcolorizedstyle'), ('TurquoiseStyle', 'Turquoisestyle'), ('LightGreenStyle', 'Lightgreenstyle'), ('DarkGreenStyle', 'Darkgreenstyle'), ('DarkGreenBlueStyle', 'Darkgreenbluestyle'), ('BlueStyle', 'Bluestyle')], max_length=100),
        ),
    ]
