# Generated by Django 3.2.4 on 2021-06-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0003_auto_20210609_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='panel_type',
            field=models.CharField(choices=[('lang-pie', 'pie chart of languages used'), ('lang-bar', 'bar chart of languages used')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardpanel',
            name='style',
            field=models.CharField(choices=[('DefaultStyle', 'DefaultStyle'), ('DarkSolarizedStyle', 'DarkSolarizedStyle')], default='DefaultStyle', max_length=40),
        ),
    ]
