# Generated by Django 3.2.4 on 2021-06-09 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github_dashboards', '0004_auto_20210609_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardpanel',
            name='panel_type',
            field=models.CharField(choices=[('lang-pie', 'pie chart of languages used'), ('lang-bar', 'bar chart of languages used')], default='lang-bar', max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardpanel',
            name='style',
            field=models.CharField(choices=[('DefaultStyle', 'Defaultstyle'), ('DarkSolarizedStyle', 'Darksolarizedstyle'), ('LightSolarizedStyle', 'Lightsolarizedstyle'), ('LightStyle', 'Lightstyle'), ('CleanStyle', 'Cleanstyle'), ('RedBlueStyle', 'Redbluestyle'), ('DarkColorizedStyle', 'Darkcolorizedstyle'), ('LightColorizedStyle', 'Lightcolorizedstyle'), ('TurquoiseStyle', 'Turquoisestyle'), ('LightGreenStyle', 'Lightgreenstyle'), ('DarkGreenStyle', 'Darkgreenstyle'), ('DarkGreenBlueStyle', 'Darkgreenbluestyle'), ('BlueStyle', 'Bluestyle')], default='DefaultStyle', max_length=40),
        ),
    ]
