# Generated by Django 3.2.4 on 2021-06-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0005_auto_20210609_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('panels', models.ManyToManyField(to='github_dashboards.DashboardPanel')),
            ],
        ),
    ]
