# Generated by Django 3.2.4 on 2021-06-09 06:02

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github_dashboards', '0006_panelscollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='creator',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
