# Generated by Django 3.2.4 on 2021-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0008_auto_20210609_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='panel_type',
            field=models.CharField(choices=[('Pie', 'pie chart of languages used'), ('Bar', 'bar chart of languages used')], default='lang-bar', max_length=100),
        ),
    ]
