# Generated by Django 3.2.4 on 2021-06-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0009_alter_dashboardpanel_panel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='panel_type',
            field=models.CharField(choices=[('Pie', 'pie chart of languages used'), ('Bar', 'bar chart of languages used')], default='Bar', max_length=100),
        ),
    ]
