# Generated by Django 3.2.4 on 2021-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0011_alter_dashboardpanel_panel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='panel_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=20),
        ),
    ]
