# Generated by Django 3.2.4 on 2021-06-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0012_dashboardpanel_panel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='panel_type',
            field=models.CharField(choices=[('Table', 'table-all user repos'), ('Pie', 'pie chart'), ('Bar', 'bar chart'), ('HorizontalBar', 'horizontal bar chart'), ('Gauge', 'gauge chart'), ('Dot', 'dot chart'), ('Treemap', 'treemap chart')], default='Bar', max_length=100),
        ),
    ]
