# Generated by Django 3.2.4 on 2021-06-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0014_alter_dashboardpanel_panel_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanelsCollection',
            new_name='PanelCollection',
        ),
    ]
