# Generated by Django 3.2.4 on 2021-06-10 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0015_rename_panelscollection_panelcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardpanel',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='panelcollection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelcollection',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
