# Generated by Django 3.2.4 on 2021-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0017_panelcollection_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpanel',
            name='svg',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
