# Generated by Django 3.2.4 on 2021-06-11 08:41

import apps.github_dashboards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0018_dashboardpanel_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='svg',
            field=models.TextField(blank=True, default=apps.github_dashboards.models.Panel.get_chart, editable=False, null=True),
        ),
    ]
