# Generated by Django 3.2.4 on 2021-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0019_alter_dashboardpanel_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='svg',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
