# Generated by Django 3.2.4 on 2021-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0021_auto_20210612_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
