# Generated by Django 3.2.4 on 2021-06-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0022_alter_dashboardpanel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='panel_size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], default='Medium', max_length=20),
        ),
    ]
