# Generated by Django 3.2.4 on 2021-06-15 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github_dashboards', '0024_alter_dashboardpanel_panel_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_type', models.CharField(choices=[('TableOfRepos', 'table- ALL repos for user'), ('Pie', 'pie chart- 1 repo\n'), ('Bar', 'bar chart- 1 repo'), ('HorizontalBar', 'horizontal bar chart- 1 repo'), ('Gauge', 'gauge chart- 1 repo'), ('Dot', 'dot chart- 1 repo'), ('Treemap', 'treemap chart- 1 repo')], default='Bar', max_length=100)),
                ('github_username', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('panel_style', models.CharField(choices=[('DefaultStyle', 'Defaultstyle'), ('DarkSolarizedStyle', 'Darksolarizedstyle'), ('LightSolarizedStyle', 'Lightsolarizedstyle'), ('LightStyle', 'Lightstyle'), ('CleanStyle', 'Cleanstyle'), ('RedBlueStyle', 'Redbluestyle'), ('DarkColorizedStyle', 'Darkcolorizedstyle'), ('LightColorizedStyle', 'Lightcolorizedstyle'), ('TurquoiseStyle', 'Turquoisestyle'), ('LightGreenStyle', 'Lightgreenstyle'), ('DarkGreenStyle', 'Darkgreenstyle'), ('DarkGreenBlueStyle', 'Darkgreenbluestyle'), ('BlueStyle', 'Bluestyle')], default='DefaultStyle', max_length=40)),
                ('panel_size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], default='M', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('svg', models.TextField(blank=True, editable=False, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DashboardPanel',
        ),
        migrations.AlterField(
            model_name='panelcollection',
            name='panels',
            field=models.ManyToManyField(to='github_dashboards.Panel'),
        ),
    ]
