# Generated by Django 3.2.4 on 2021-06-15 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github_dashboards', '0027_auto_20210615_0520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanelCollection',
            new_name='PanelsCollection',
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_style',
            field=models.CharField(blank=True, choices=[('DefaultStyle', 'Defaultstyle'), ('DarkSolarizedStyle', 'Darksolarizedstyle'), ('LightSolarizedStyle', 'Lightsolarizedstyle'), ('LightStyle', 'Lightstyle'), ('CleanStyle', 'Cleanstyle'), ('RedBlueStyle', 'Redbluestyle'), ('DarkColorizedStyle', 'Darkcolorizedstyle'), ('LightColorizedStyle', 'Lightcolorizedstyle'), ('TurquoiseStyle', 'Turquoisestyle'), ('LightGreenStyle', 'Lightgreenstyle'), ('DarkGreenStyle', 'Darkgreenstyle'), ('DarkGreenBlueStyle', 'Darkgreenbluestyle'), ('BlueStyle', 'Bluestyle')], default='', max_length=40, null=True),
        ),
    ]
