# Generated by Django 3.2.4 on 2021-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0028_auto_20210615_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='repo_name',
            field=models.CharField(max_length=100),
        ),
    ]
