# Generated by Django 3.2.4 on 2021-06-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0030_alter_panel_repo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='repo_name',
            field=models.CharField(max_length=100),
        ),
    ]
