# Generated by Django 3.2.4 on 2021-06-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_dashboards', '0031_alter_panel_repo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='repo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
