# Generated by Django 3.2.4 on 2021-06-29 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github_dashboards', '0034_alter_panel_panel_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='panel_type',
            field=models.CharField(choices=[('TableOfRepos', 'table- ALL repos for user'), ('Pie', 'pie chart- 1 repo'), ('Bar', 'bar chart- 1 repo'), ('HorizontalBar', 'horizontal bar chart- 1 repo'), ('Gauge', 'gauge chart- 1 repo'), ('Dot', 'dot chart- 1 repo'), ('Treemap', 'treemap chart- 1 repo')], default='Bar', max_length=100),
        ),
        migrations.AlterField(
            model_name='panelscollection',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
